### ISSUE TITLE
[Production only] Unable to connect: tls://gateway.push.apple.com:2195: 2 (stream_socket_client(): Failed to enable crypto)

### ISSUE THREAD

**Issue by adrienthiery** [davibennun/laravel-push-notification#110]
Hi there, 

I spent the whole day trying to figure that out but without result.

When I setup my push-notification config to work in development mode, everything works fine, I receive the push notifications on my iPhone when I run the app from XCode (so in development mode).

On the same server, when I switch the config to `production` and use the production certificate (I checked if it was working fine with the `openssl` command, `return 0 (ok)` is the answer for apple's server), I get : 

```
RuntimeException in AbstractClient.php line 112:
Unable to connect: tls://gateway.push.apple.com:2195: 2 (stream_socket_client(): Failed to enable crypto)

in AbstractClient.php line 112
at AbstractClient->connect('tls://gateway.push.apple.com:2195', array('local_cert' => 'pathToMyCertificate', 'passphrase' => 'MyPassPhrase')) in AbstractClient.php line 79
at AbstractClient->open('1', '/pathToMyCertificate', 'MyPassPhrase') in Apns.php line 117
at Apns->getOpenedClient(object(Message)) in Apns.php line 62
at Apns->push(object(Push)) in PushManager.php line 67
at PushManager->push() in App.php line 34
...
```

I recreated my certificates 10 times, checked the permissions on the files, checked the certificates, tried a whole bunch of things found on the internet without success.

Any idea or leads I could follow?

Thanks a lot.

**Comment by adrienthiery** [comment]
For anybody who has issues with Apple freaking certificates, use https://fastlane.tools/ !

Solved my problem in less than 5 minutes.

**Comment by manishios** [comment]
How does shifting to pem solved your issue. I think you already had the pem file when you tried to connect to the APNS. I am facing the same issue. Please explain.

**Comment by adrienthiery** [comment]
I must have been doing something wrong the way I was generating the pem file manually with the apple developers portal and the certificates things... But the certificate generated by pem works.

Also, the certificate that I had generated by hand was saying no problem when doing a connection to the APNs by hand (with an openssl command in the terminal) so maybe pem does something else to allow it to work correctly with PHP...

**Comment by sarveshamrit** [comment]
@adrienthiery how to generate pem using https://fastlane.tools/  can u guide me please i am also having same issue push doesn't go to ios from server but it goes via pushtry.com strange
