### ISSUE TITLE
Unable to set private key file

### ISSUE THREAD

**Issue by Hamiid** [davibennun/laravel-push-notification#113]
I'm trying to send ios notification but I get this error: 
`Unable to connect: tls://gateway.sandbox.push.apple.com:2195: 2 (stream_socket_client(): Unable to set private key file /certificate/path.pem)`
Here is my config: 
`    'appNameIOS'     => array(
        'environment' =>'development',
        'certificate' =>'../certificate.pem',
        'passPhrase'  => 'passPhrase',
        'service'     =>'apns'
    ),`

But after I remove the quotes from `passPhrase` I just getting `HTTP error 500` without any error on response body. 

I created `.pem` files from [https://www.airpair.com/ionic-framework/posts/push-notifications-using-ionic-framework](url) step by step.

NOTE: I'm using MAMP server.

**Comment by charlie-s** [comment]
Were you able to resolve? I see that you closed this about a week after opening.

**Comment by Hamiid** [comment]
@charlie-s I had a problem with certificate files. After googling I found the true way to export my certificate files. After that my problem was solved.

**Comment by drpiou** [comment]
@charlie-s what is the true way? thanks for your help :)
