### ISSUE TITLE
Class 'Sly\NotificationPusher\Adapter\' not found

### ISSUE THREAD

**Issue by aliuwahab21** [davibennun/laravel-push-notification#13]
Please can you help me figure that thing out. I am using laravel 4.1

**Comment by cfv1000** [comment]
Hey

Your config key does not exist

```php
PushNotification::app($key)
```

Make sure that key exists in given path. This is usually fixed with

```
php artisan config:publish davibennun/laravel-push-notification
```

**Comment by fredbombadil** [comment]
I am having this problem, but my config file is published and set up with the proper API key and app name - any suggestions?

**Comment by davibennun** [comment]
@fredbombadil Please double check your config files

**Comment by theronin** [comment]
@davibennun I have the same issue, published config file and the config file is correct.

**Comment by melvinmmw** [comment]
having the same issue here as well. using laravel 5.2

**Comment by 4QStudios** [comment]
same issue laravel 5.2

**Comment by anilkumar201241** [comment]
anybody has solved that issue. I have the same issue
