### ISSUE TITLE
Push notification is not being delivered to device

### ISSUE THREAD

**Issue by tahirwaseer** [davibennun/laravel-push-notification#135]
I have followed all steps for configuring the package but I am unable to receive notification on apple device. Here is my server code to send notification;
            `$pn = PushNotification::app('iOS')->to('b2ae8b68fff1fbbe957b8b8f703744794d89f09d45f69b2d847a26c3b064e268')->send('Hello');`
`dd($pn); // just printed out see whats going on with push manager 
`
Here is the dd() function output; 
![screen shot 2016-08-22 at 4 26 43 pm](https://cloud.githubusercontent.com/assets/9745802/17853484/23029302-6886-11e6-8cf0-cb05730dfff6.png)
I have added correct certificates for push as well in config file. I really don't get why it is not being delivered.

**Comment by fzhan** [comment]
Same here, everything correct, not being sent

**Comment by sannysinghs** [comment]
Hi @tahirwaseer , have you found any solution on this  ?

**Comment by tahirwaseer** [comment]
Yes I've done it but using my own code for sending push notifications.

**Comment by mattpramschufer** [comment]
I am having the same issue.  Based on responses from a bunch of folks with issues, I guess I need to simply write my own

**Comment by tahirwaseer** [comment]
Actually I've struggled a lot in order to get it working. But at the end it was quite simple just make sure that you are generating certificates correctly and then just use a simple PHP script for socket connection to apple server. And that's all that you need to get it working.

**Comment by mattpramschufer** [comment]
Yeah the issue that I found out is that if you are using TestFlight builds they are NOT sandbox, they utilize the production cert and server.

**Comment by tahirwaseer** [comment]
I think the original issue was resolved and was related to APNS certificate generation.
