### ISSUE TITLE
Set certificate dynamically

### ISSUE THREAD

**Issue by digital-dog** [davibennun/laravel-push-notification#14]
Is it currently possible to set the certificate programmatically? We have a need to use multiple certificates which will be selected at runtime and not in the config file.

If not, I'll fork and implement.

Thanks

**Comment by elieandraos** [comment]
i had the same issue, i ended up writing the config file dynamically. it works, but a database configuration would be ideal.

**Comment by davibennun** [comment]
Never its too late, 314497ad52a4923f5227bc62c4c7cbdde9b4d847

**Comment by elieandraos** [comment]
I did re-write the config file too. database would be ideal @davibennun
