### ISSUE TITLE
Sly \ NotificationPusher \ Exception \ PushException 401 Forbidden; Authentication Error

### ISSUE THREAD

**Issue by aliuwahab21** [davibennun/laravel-push-notification#15]

**Comment by natsu90** [comment]
Hey guys, anyone have figured this error? I have left the IP empty but still get the error.

**Comment by natsu90** [comment]
Okay I have to enable Google Cloud Messaging for Android in Google console, http://stackoverflow.com/a/26924498/1109004. Silly me.
