### ISSUE TITLE
Device token must be mask "/[^0-9a-f]/". Token given: ".........."

### ISSUE THREAD

**Issue by raj82q** [davibennun/laravel-push-notification#158]
'iOS' => array(
        'environment' =>'production',
        'certificate' =>'storage/public/key/ios/APNS_cert.pem',
        'passPhrase'  =>'',
        'service'     =>'apns'
    )

$os = "iOS";
        $token = "1111111111111111111111111111111111111111111111111111111";
        $string = "EURO MAX is scheduled to arrive at 2017-05-09 and is scheduled to depart on 2017-04-08";
        PushNotification::app($os)->to($token)->send($string);

So I want to know is passphrase mandatory in iOS Case ????

**Comment by iamrutvik** [comment]
Having same issue. Urgent Help needed.

**Comment by raj82q** [comment]
Rutvik I guess pass phase is mandatory with davibennun laravel-push-notification so i shifted to custom notification for iOS and that worked

**Comment by sachinsolanki** [comment]
I found the solution below its working for me.

/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Message.php
Change from

if (preg_match('/[^0-9a-f]/', $token)) {
throw new Exception\InvalidArgumentException(sprintf(
'Device token must be mask "%s". Token given: "%s"',
'/[^0-9a-f]/',
$token
));
}

TO

if (preg_match('/[^0-9a-fA-F]/', $token)) {
throw new Exception\InvalidArgumentException(sprintf(
'Device token must be mask "%s". Token given: "%s"',
'/[^0-9a-f]/',
$token
));
}

**Comment by sachin** [comment]
change the device_id to lower case

PushNotification::app($os)->to(strToLower($token))->send($string);
