### ISSUE TITLE
Upgrading to Laravel 5.4 - Application::share issue

### ISSUE THREAD

**Issue by byhbt** [davibennun/laravel-push-notification#159]
I just upgraded to Laravel 5.4 and see this issue.
```
Call to undefined method Illuminate\Foundation\Application::share()
vendor/davibennun/laravel-push-notification/src/Davibennun/LaravelPushNotification/LaravelPushNotificationServiceProvider.php:35
```

Any updates from the package yet?

**Comment by sisve** [comment]
Relevant; your composer.json claims compatibility with 5.* (`"illuminate/support": "5.*"`), which is incorrect. Laravel does not use semver, and there's no promise of compatibility between 5.1, 5.2, etc. It would be better to limit yourself to tested versions; `"illuminate/support": "5.1.*|5.2.*|5.3.*"` to avoid these incompatibility issues.

**Comment by davibennun** [comment]
https://github.com/davibennun/laravel-push-notification/pull/160
