### ISSUE TITLE
push notifications do not sent after certificate renew

### ISSUE THREAD

**Issue by snoooopx** [davibennun/laravel-push-notification#196]
Hi there,
I have problem with push notifications. After certificate renew the push notifications do not sent. 
Could you please advise a solution for that issue.

Thanks in advance.

**Comment by WilsonFpz** [comment]
same here

**Comment by carlesAlterego** [comment]
I'm having same issue, did you find a solution?

Thanks!

**Comment by sarveshamrit** [comment]
@snoooopx how did you resolve sir? can u help @WilsonFpz also sir? did u resolved yours?

**Comment by snoooopx** [comment]
> @snoooopx how did you resolve sir? can u help @WilsonFpz also sir? did u resolved yours?

Hi, try to clear cache or run _php artisan optimize_

**Comment by sarveshamrit** [comment]
@snoooopx  sir i tried this actually push goes to android but it doesn't go to ios device , i even tried cli method of sly but didn't go, but it goes through pushtry.com, i have configured pem files as well on server its just from lumen framework backend it doesn't go
