### ISSUE TITLE
Unable to connect: tls://gateway.sandbox.push.apple.com:2195: 2 (stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version)

### ISSUE THREAD

**Issue by taynv28892** [davibennun/laravel-push-notification#201]
Hi,
I encountered this error when trying to push notification with **development environment** for iOS devices .
My config:
`return array(
    'appNameIOS'     => array(
        'environment' =>'development',
        'certificate' => storage_path('certificates/push.pem'),
        'passPhrase'  =>'1',
        'service'     =>'apns'
    ),
    'appNameAndroid' => array(
        'environment' =>'production',
        'apiKey'      =>'yourAPIKey',
        'service'     =>'gcm'
    )
);`

Server: EC2 (Amazon Linux AMI)
PHP version: 5.6.32
OpenSSL version: 1.0.2k

When I try to change **tls** to **ssl or tlsv1.1 or tlsv1.2** protocol  in file 

> /vendor/zendframework/zendservice-apple-apns/src/Apns/Client/Message.php

 it working as well.

Please help me. Thank all!

**Comment by janek109** [comment]
Problem is with this class in this line:

https://github.com/zendframework/ZendService_Apple_Apns/blob/master/src/Apns/Client/AbstractClient.php#L99

so you can't set version of protocol. 

Probably in line 105 should be sth like

stream_context_create([
    'ssl' => [
        'crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT |
                           STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT,
    ],
]);

or in line 70

$sslOptions = [
            'local_cert' => $certificate,
            'crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT |
                           STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT,
        ];

**Comment by janek109** [comment]
Zend was fixed on that issue in

https://github.com/zendframework/ZendService_Apple_Apns/releases/tag/release-1.4.0

**Comment by taynv28892** [comment]
> Zend was fixed on that issue in
> 
> https://github.com/zendframework/ZendService_Apple_Apns/releases/tag/release-1.4.0

Thank you for reply. I've found the solution for this issue. It is similar to the change of the Zend service team.
