### ISSUE TITLE
How to check notification sent or not

### ISSUE THREAD

**Issue by umairali** [davibennun/laravel-push-notification#22]
Please tell me how to check notification sent or not

**Comment by canfiax** [comment]
I'd like this feature as well!

**Comment by canfiax** [comment]
Check my pull request here: https://github.com/davibennun/laravel-push-notification/pull/27

To get feedback from APNS do:

	$push = PushNotification::app('MyApp')
					->to($devices)
					->send($message);

	dd($push->getFeedback()); // the feedback

**Comment by davibennun** [comment]
Pull request #27 by canfiax merged

**Comment by koray-mobven** [comment]
Pusb is sent but getFeedback returns null. Why?

**Comment by mansouralex** [comment]
What is the response for getFeedback() method to consider that the notification has been sent successfully? Anybody?

**Comment by SumithraRajan** [comment]
Notification service is working well... To get response message I'm using this code,
foreach ($collection->pushManager as $push) {
        $response = $push->getAdapter()->getResponse();
    }It is working well.  But nowadays i didin't get any response from $push. $collection collect response but can't convert in to code
