### ISSUE TITLE
Symfony\Component\OptionsResolver\OptionsResolverInterface  was deprecated

### ISSUE THREAD

**Issue by sirsquall** [davibennun/laravel-push-notification#26]
Hi,

The "Symfony\Component\OptionsResolver\OptionsResolverInterface" interface was deprecated in version 2.6 and will be removed in 3.0. Use "Symfony\Component\OptionsResolver\OptionsResolver" instead.

**Comment by canfiax** [comment]
I am getting this error as well

**Comment by davibennun** [comment]
Please refer to https://github.com/Ph3nol/NotificationPusher
