### ISSUE TITLE
'content-available' key within 'aps' dictionary

### ISSUE THREAD

**Issue by Illizian** [davibennun/laravel-push-notification#29]
I'm having difficulty sending a push notification to an iOS device containing the key 'content-available' within the aps dictionary, as documented on Table 3-1 [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html).

Having dug around, it appears the origin of the issue is possibly within the [ZendService\Apple\Apns\Message\Alert](https://github.com/zendframework/ZendService_Apple_Apns/blob/master/library/ZendService/Apple/Apns/Message/Alert.php) class.

I'm happy to create a PR for this fix but am looking for some guidance on whether this will need to be done within the Zend repo, or whether we can achieve it with this library?

**Comment by davibennun** [comment]
Hi,
This lib just wraps Ph3nol/NotificationPusher, that uses ZendService classes, so you should submit a PR on Zend APNS class itself.

**Comment by Illizian** [comment]
That's what I thought - just wanted to check first

**Comment by nadeemkhoury** [comment]
@Illizian Can you tell me how can I fix it ?? I'm facing the same problem. should I update this package or what should I do ??

**Comment by Illizian** [comment]
@nadeemkhoury I've had a look down the dependency chain and all look's well. Check your installed version of `zendframework/ZendService_Apple_Apns`, the relevant PR is [here](https://github.com/zendframework/ZendService_Apple_Apns/pull/23)
