### ISSUE TITLE
How to trouble shoot the push notification??

### ISSUE THREAD

**Issue by tonychan818** [davibennun/laravel-push-notification#32]
I have set the cert in app/config/packages/davibennun/laravel-push-notifcation/config.php

and made a testing function like this and hardcoded the devicetoken to it.
\PushNotification::app('CP2')->to("mydevicetoken")->send('Hello World, i`m a push message');

the function run without error, but my iphone didnt' get the notification. 
how can I troubleshoot this issue??

**Comment by davibennun** [comment]
There is a lot of things that can go wrong, check your certificates, app, device, network, etc.
Try to googling a complete guide for sending apns push notifications and follow it strictly

**Comment by commandantp** [comment]
@tonychan818 Hi! Facing the same here, did you find anything useful I should look for ?
