### ISSUE TITLE
Laravel 5 Compatibility

### ISSUE THREAD

**Issue by ellisthedev** [davibennun/laravel-push-notification#34]
Hello,

Me and my company are getting ready to integrate Push Notifications into our application. However, we are developing on Laravel 5. Is there an ETA on getting this updated to be compatible with L5?

Cheers,
Andrew

**Comment by davibennun** [comment]
I havent played with laravel 5 yet, can you fork the repo and upgrade illuminate/support version constraint to "4.*|5.*" and see if its ok?

**Comment by ellisthedev** [comment]
I'll take a peak this weekend for ya.

**Comment by billmn** [comment]
To allows L5 compatibility need to change come code like configuration publishing ...

I propose to create a new branch dedicated to L5 version.

**Comment by nullproduction** [comment]
I'd like use this lib in laravel 5 too.

**Comment by billmn** [comment]
I think we have to convert code to PSR-4 before working on a L5 support.

I can work on PSR-4 tonight.

**Comment by kisPocok** [comment]
+1 upvote!

**Comment by asterism612** [comment]
+1

**Comment by torniker** [comment]
:+1:

**Comment by yvesroos** [comment]
👌

**Comment by Daniel-Seo** [comment]
+1

**Comment by gmatkowski** [comment]
+1

**Comment by kirant400** [comment]
+1

**Comment by wanchopeblanco** [comment]
+1

**Comment by davibennun** [comment]
Hello guys!
Sorry for being late. Laravel 5 version is now available at laravel5 branch, you can require it on composer:
```"davibennun/laravel-push-notification": "dev-laravel5" ```
 The way you use this package is the same, the only thing changed was the config file location, once you published it using php ```artisan vendor:publish``` the config file goes to ```app/config/push-notification.php```

**Comment by davibennun** [comment]
I don't have any certificate here to fully test the package, I think its ok since changes were very small, but you never know... can someone use it in real life just to make sure everything is working?

**Comment by gmatkowski** [comment]
i'll be able to test it in a few days.

**Comment by nullproduction** [comment]
@davibennun Thank U. I will check this next week

**Comment by agarwalVinayak** [comment]
I am trying for Laravel 5. 
config:publish is not valid command 

So For Copy the config file into your project by running
php artisan config:publish davibennun/laravel-push-notification doesn't worked in Laravel 5

Instead this will work laravel 5 : 
php artisan vendor:publish --provider="Davibennun\LaravelPushNotification\LaravelPushNotificationServiceProvider" --tag="config"

This command will created config file in L5.

**Comment by davibennun** [comment]
@agarwalVinayak I just merged the pull request that updates the documentation.

**Comment by agarwalVinayak** [comment]
@davibennun  cool!! , but still doc for L5 have composer.json path
as "davibennun/laravel-push-notification": "dev-master"
and not 
"davibennun/laravel-push-notification": "dev-laravel5"
