### ISSUE TITLE
Android Push Noification

### ISSUE THREAD

**Issue by kuldeep1984** [davibennun/laravel-push-notification#37]
Hi, 

I am newbie and using laravel 4 with this package. Want to know what is the "$deviceToken"
in the follwing code -

PushNotification::app('appNameIOS')
                ->to($deviceToken)
                ->send('Hello World, i`m a push message');

And how to get this $device token? PLease Help!

**Comment by fmendoza** [comment]
You should get the token from your app code, after that, you send the token to server and then, store it in database.
