### ISSUE TITLE
how to set optional parameters in Android GCM

### ISSUE THREAD

**Issue by sannysinghs** [davibennun/laravel-push-notification#39]
I am trying to set keys like "collapseKey" and "delayWhileIdle" in GCM . I have no idea how to set those keys . This is how I set keys . 
```
$message = PushNotification::Message($msg,array(
		    'msgcnt'=> 1,
	        'title'=>$event->title,
	        'collapseKey' => 'invited' 
));

```
According to this collaposeKey is not working . And it is also inside payload of GCM instead .
any idea ? thanks

**Comment by sannysinghs** [comment]
Can anybody help me , i am really stuck here . can not proceed . Appreciate

**Comment by omenocal** [comment]
Hello @sannysinghs . You can check my project:
https://github.com/omenocal/GCM-Laravel

I hope it could help you !!

**Comment by kanashin** [comment]
@sannysinghs Did you found a solution? Thank you!

**Comment by sannysinghs** [comment]
hi @kanashin  , i have been struggled some times to get the solution. For me what did solve is I looked into files , esp Message.php and Client.php which is located in vendor/zendframework/zendservice-google-gcm/library/ZendService/Google/Gcm . After reading thru those files , i've got some idea how its worked and finally i got what i looked for. Hopefully , it might work for you

**Comment by kanashin** [comment]
@sannysinghs Yes! It was enough doing $push->adapter->setParameter and then use $push->send.


Thank you!
