### ISSUE TITLE
 Device token must be mask "/[^0-9a-f]/". Token given: "TOKEN........" 

### ISSUE THREAD

**Issue by vuhung3990** [davibennun/laravel-push-notification#41]
config : 
`'appNameIOS'=>array(
        'environment' => 'development',
        'certificate' => base_path(). '\pushProd.pem',
        'passPhrase'  => '',
        'service'     => 'apns'
    )`
and `PushNotification::app('appNameIOS')->to("FA87F3994E03640A370F4EC5E5F2337B5CCBF4A155595FADDBE81DCD0DF47A03")
                ->send('Hello World, im a push message');` it got error, sorry i don't know english

**Comment by wanchopeblanco** [comment]
You have to set your certificate passphrase.
