### ISSUE TITLE
Tip: User device token

### ISSUE THREAD

**Issue by marijang** [davibennun/laravel-push-notification#42]
I need advice
How to store user device token?
ex.
When  user on iphone login into app then I store his token?Keep that token hole time?
When user log out then remove or delete token?

What about when user decide to remove app? I will get response from apple so I can remove token?

Thanks

**Comment by wanchopeblanco** [comment]
Hi @marijang ,

This package doesnt store the device token, you must create your database table, model and controllers to do this and then get the device token to send the messages to it.

About removing the app, theres a method supposed to get the response if the device has uninstalled the app, but at this moment i dont know how to use it correctly is doesnt returning any value.

**Comment by ArnoVanBiesen** [comment]
I'm new to laravel and the whole push notifications system i have a problem. This will probably be a stupid question but how do i get the device token?

**Comment by wanchopeblanco** [comment]
You need to get the device token from the device, look at this link for further reading

http://stackoverflow.com/questions/8798725/get-device-token-for-push-notification
