### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by kadirarlii** [davibennun/laravel-push-notification#47]
Hello,

My error is "Maximum execution time of 30 seconds exceeded" after push notification to iOS.

protected function read($length = 1024)
    {
        if (!$this->isConnected()) {
            throw new Exception\RuntimeException('You must open the connection prior to reading data');
        }
        $data = false;
        if (!feof($this->socket)) {
            **$data = fread($this->socket, (int) $length);**//this line 
        }

I use Laravel4..

**Comment by JavierMartinz** [comment]
It's happening to me also. It seems to be related to https://github.com/Ph3nol/NotificationPusher/issues/46#issuecomment-100525275

**Comment by kadirarlii** [comment]
I didn't found solution this link :(

**Comment by mithrann** [comment]
its happening to me also. But only when i change the environment to production :(
