### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by wislem** [davibennun/laravel-push-notification#48]
I think this package is a must have for those of us trying to cook Lumen APIs for mobile apps :)

Thank you for a great package!

**Comment by iffifan** [comment]
I think you can use laravel5 version with lumen

**Comment by wislem** [comment]
Lumen does not support config files, and this packages depends heavily on configuration.

I think that you can actually make Lumen support configuration files but doing it will stop Lumen from beeing what it was intended to be.

**Comment by davibennun** [comment]
Now supporting Lumen: b703b0fe02719a540139f5d26b73ac53a198b50d

**Comment by natsu90** [comment]
Hey guys, I'm getting `Class 'PushNotification' not found`, what did I miss?

**Comment by natsu90** [comment]
Okay I have to add following line to `bootstrap/app.php`, `$app->register('Davibennun\LaravelPushNotification\LaravelPushNotificationServiceProvider');`, and `use Davibennun\LaravelPushNotification\Facades\PushNotification;` in controller.

**Comment by davibennun** [comment]
Are you using lumen? If so, first ```$app->withFacades();``` then ```class_alias('Davibennun\LaravelPushNotification\Facades\PushNotification', 'PushNotification');```

**Comment by natsu90** [comment]
Yes I'm using lumen 5.1. I already uncommented `$app->withFacades();`. I suppose `class_alias ` is the same as `use`. If I don't add `$app->register('Davibennun\LaravelPushNotification\LaravelPushNotificationServiceProvider');` I will get this error; `Class pushNotification does not exist`.

**Comment by davibennun** [comment]
Yes i forgot to mention, but you have to register the package service provider to use it, are you still getting erros after registering the service provider, enabling facades and aliasing classes?

**Comment by natsu90** [comment]
No, already get it working. Thanks.
