### ISSUE TITLE
ERROR install package 

### ISSUE THREAD

**Issue by altpoint** [davibennun/laravel-push-notification#52]
after    composer update throw

Exception: Class pushNotification does not exist
Skipping \Davibennun\LaravelPushNotification\Facades\PushNotification.

WTF?!

This fuck in https://github.com/davibennun/laravel-push-notification/blob/master/src/Davibennun/LaravelPushNotification/Facades/PushNotification.php#L12

change pushNotification to **P**ushNotification

**Comment by thiagovictorino** [comment]
Did u try composer dump-autoload?

**Comment by altpoint** [comment]
**Exception: Class pushNotification does not exist** 
first letter in class name is **lowercase**, must be uppercase!

> composer dump-autoload ← It did not help and does not help

**Comment by davibennun** [comment]
The facade is named ```PushNotification```, the lowercase p is only used for the IoC container, not the class itself.

**Comment by altpoint** [comment]
но composer в autoload пропускает этот класс и ничего в результате не работает, я поменял и всё завелось

**Comment by davibennun** [comment]
This package registers itself on the IoC container with ```pushNotification``` key [see here](https://github.com/davibennun/laravel-push-notification/blob/master/src/Davibennun/LaravelPushNotification/LaravelPushNotificationServiceProvider.php#L32), so the [facade accessor](https://github.com/davibennun/laravel-push-notification/blob/master/src/Davibennun/LaravelPushNotification/Facades/PushNotification.php#L12) must also be  ```pushNotification```.
