### ISSUE TITLE
Non-static method Davibennun\LaravelPushNotification\PushNotification::app() should not be called statically. What?

### ISSUE THREAD

**Issue by Radmess** [davibennun/laravel-push-notification#67]
I followed the instructions, but when I try to test it from the controller, I get this error: 
Non-static method Davibennun\LaravelPushNotification\PushNotification::app() should not be called statically, assuming $this from incompatible context. 

I AM supposed to have a 'use Davibennun\LaravelPushNotification\PushNotification;' at the top, right? 

Without the 'use' I get: Class 'App\Http\Controllers\PushNotification' not found. 

Any ideas what went wrong? 

Using Laravel 5.1.

**Comment by davibennun** [comment]
You have to set up the facade by adding ```'PushNotification' => 'Davibennun\LaravelPushNotification\Facades\PushNotification'``` to the alias array in your config file

**Comment by Radmess** [comment]
![pushnot](https://cloud.githubusercontent.com/assets/5732434/9850885/f05f125c-5af5-11e5-8832-dc379413ef03.PNG)

Pretty sure I've already done that. 
Like this?

And then run composer update? and 
php artisan vendor:publish --provider="Davibennun\LaravelPushNotification\LaravelPushNotificationServiceProvider" --tag="config"

**Comment by Radmess** [comment]
Problem solved (I think). Needed to have "use Pushnotification" instead of  'use Davibennun\LaravelPushNotification\PushNotification;'
