### ISSUE TITLE
can not use push-notification 'Failed to enable crypto'

### ISSUE THREAD

**Issue by LiangJianle** [davibennun/laravel-push-notification#75]
ErrorException in AbstractClient.php line 102:
Failed to enable crypto

in AbstractClient.php line 102
at HandleExceptions->handleError('2', 'Failed to enable crypto', '/home/vagrant/Code/PersonalInfoPushCenter/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Client/AbstractClient.php', '102', array('errno' => '0', 'errstr' => '', 'host' => 'tls://gateway.sandbox.push.apple.com:2195', 'ssl' => array('local_cert' => '/home/vagrant/Code/PersonalInfoPushCenter/ck.pem', 'passphrase' => '')))

my environment is Laravel 5.1 + Homestead + HHVM

And i found Same question here.

Appears the HHVM devs are aware of it and have added it to their TODO list.. facebook/hhvm#1647

**Comment by joaorobertopb** [comment]
Hi,

I have the same problem...

Help !!

**Comment by joaorobertopb** [comment]
http://stackoverflow.com/questions/28283789/cannot-establish-ssl-connection-with-composer-with-php-5-6-3/28284774#28284774 

in my case, it did not work! 

Help!!!!

**Comment by LiangJianle** [comment]
when I turn off the HHVM, the question not appear again.
Is the path of certificate right?

my file : push-notification.php

    'appNameIOS'     => array(
        'environment' =>'development',
        'certificate' => storage_path('ck.pem'),
        'passPhrase'  =>'123456',
        'service'     =>'apns'
    ),

**Comment by efriandika** [comment]
is it solved ? i got same error..

**Comment by LiangJianle** [comment]
turn off the HHVM,i solved the problem..
modified the .yaml file  which located in ~/.homestead/Homestead.yaml, 
set hhvm to false;

like this:

sites:
    - map: homestead.app
      to: /home/vagrant/Code/PersonalInfoPushCenter/public
      hhvm: false
