### ISSUE TITLE
[iOS] Error Device token must be mask "/[^0-9a-f]/"  - Laravel 4.2

### ISSUE THREAD

**Issue by dzung1nguyen** [davibennun/laravel-push-notification#83]
Hi Guys,

I am using laravel 4.2 and current i have  a bug when push notification to iOS.

This's  bug:

Device token must be mask "/[^0-9a-f]/". Token given: "96133C211DB1E54E0C1310EC43C628D341B568C9C612FBCEA97C2D0ECD75B2C6"

Before, i worked, but recently, it's error.

Please help me.

So Thanks.

** I found solution **

/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Message.php
Change from

if (preg_match('/[^0-9a-f]/', $token)) {
            throw new Exception\InvalidArgumentException(sprintf(
                    'Device token must be mask "%s". Token given: "%s"',
                    '/[^0-9a-f]/',
                    $token
            ));
        }

TO

if (preg_match('/[^0-9a-fA-F]/', $token)) {
            throw new Exception\InvalidArgumentException(sprintf(
                    'Device token must be mask "%s". Token given: "%s"',
                    '/[^0-9a-f]/',
                    $token
            ));
        }

**Comment by joskoomen** [comment]
Put your CHMOD to 400 for the .pem file that should work

**Comment by rupalipemare** [comment]
Getting same errror even on changing to 400 the issue is not resolved. Changing any core vendor is right option as if we update composer the changes be overridden

**Comment by sachin** [comment]
change the device_id to lower case

PushNotification::app($os)->to(strToLower($token))->send($string);
