### ISSUE TITLE
sslcafile and ssclapath issue

### ISSUE THREAD

**Issue by juanjolainez** [davibennun/laravel-push-notification#9]
Hello!

I am receiving this error only in Android (iOS is working well).

'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Unable to enable crypto on TCP connection android.googleapis.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.' in /home/casper/development/vendor/zendframework/zend-http/Zend/Http/Client/Adapter/Socket.php:310

Do you know how to solve it? I've been googling a little bit but I haven't found a proper solution. 

Thank you very much! :D

**Comment by tanveerahmaddar** [comment]
thanks cdarken  this worked 
$app = PushNotification::app('appNameAndroid');

        $new_client = new \Zend\Http\Client(null, array(
            'adapter' => 'Zend\Http\Client\Adapter\Socket',
            'sslverifypeer' => false
        ));
        $app->adapter->setHttpClient($new_client);
        foreach($userPush as $push){
                $app->to($push->device_token)
                    ->send('Hello World, i`m a push message');
        }
