### ISSUE TITLE
Adapter Apns does not support XXXX token's device

### ISSUE THREAD

**Issue by abhijeetnaik** [davibennun/laravel-push-notification#96]
Hi,
I am trying to send push notification to iOS Device. certificate.pem file is correct. 
I have created a route to send out a notification to IOS device. But when i am trying to call the function, its throwing me: -
local.ERROR: exception 'Sly\NotificationPusher\Exception\AdapterException' with message 'Adapter Apns does not support XXXX token's device' in /private/var/www/pattypets/vendor/sly/notification-pusher/src/Sly/NotificationPusher/Model/Push.php:90

Please see:- Its working well and good in android.

**Comment by germanllop** [comment]
Hi, I have the same issue
Please, what's the solution?

**Comment by trevorgehman** [comment]
I'm also seeing this in some cases. What is the solution?

**Comment by pabloleone** [comment]
Me too!

**Comment by raideltorres** [comment]
I'm still having this issue, what's he solution?

**Comment by robschuh** [comment]
Hello guys, I am checking if deviceToken is valid before to send the pushNotification, something like this:

```
// Check it is a valid token.
                      if( ctype_xdigit($friend->deviceToken) && 64 == strlen($friend->deviceToken )){
                         $msgPush = 'There are new actity';
                        User::pushNotification($user, $friend, $msgPush);
                      }
```
